name: build
on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/') || inputs.publish_release_artifacts
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FROM=ghcr.io/emqx/emqx-builder/5.1-3:${{ matrix.elixir }}-${{ matrix.otp }}-debian11

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
        quic_support:
          - true
          - false
        os:
          - ubuntu22.04

    container:
      image: ghcr.io/emqx/emqx-builder/5.1-3:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: bash
        run: |
          [ "false" == ${{ matrix.quic_support }} ] && export BUILD_WITHOUT_QUIC=1
          git config --global --add safe.directory $(pwd)
          make
      - if: failure()
        run: cat rebar3.crashdump
      - name: test release
        run: |
          set -e
          mkdir test-release
          cp ./emqtt-bench*.tar.gz test-release
          cd test-release
          tar xfz ./emqtt-bench*.tar.gz
          bin/emqtt_bench
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./*.tar.gz

  mac:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - macos-12-arm64
          - macos-12
        otp:
          - 25.3.2-1

    runs-on: ${{ matrix.macos }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        run: |
          brew install curl zip unzip gnu-sed kerl unixodbc freetds
          echo "/usr/local/bin" >> $GITHUB_PATH
          git config --global credential.helper store
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.kerl
          key: otp-${{ matrix.otp }}-${{ matrix.macos }}
      - name: build erlang
        if: steps.cache.outputs.cache-hit != 'true'
        timeout-minutes: 60
        env:
          OTP: ${{ matrix.otp }}
          KERL_CONFIGURE_OPTIONS: '--disable-hipe --disable-jit'
        run: |
          set -eux
          if [ ! -d $HOME/.kerl/$OTP ]; then
            kerl build git https://github.com/emqx/otp.git OTP-$OTP $OTP
            kerl install $OTP $HOME/.kerl/$OTP
          fi
      - name: build
        env:
          OTP: ${{ matrix.otp }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_DEVELOPER_IDENTITY: ${{ secrets.APPLE_DEVELOPER_IDENTITY }}
          APPLE_DEVELOPER_ID_BUNDLE: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE }}
          APPLE_DEVELOPER_ID_BUNDLE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE_PASSWORD }}
        run: |
          . $HOME/.kerl/$OTP/activate
          make
      - if: failure()
        run: cat rebar3.crashdump
      - name: test release
        run: |
          set -e
          mkdir test-release
          cp ./emqtt-bench*.zip test-release
          cd test-release
          unzip -q ./emqtt-bench*.zip
          bin/emqtt_bench
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./*.zip
